apiVersion: elemental.cattle.io/v1beta1
kind: MachineRegistration
metadata:
  name: fireKK
  namespace: fleet-default
spec:
  config:
    cloud-config:
      users:
      - name: root
        passwd: "$6$/OBpzEc039L4Ovc3$xlXHWOm/LLarJB3mILq2IT9g3zr4aRtN6dB5M/RZfUmuaAPZkmo4L/vrJfvnhRPS23KD1NLB/SpOAErl00ShO/"
      write_files:
      - content: |
          OPTION1="yes"
          OPTION2="false"
        path: "/etc/myservice.conf"
      runcmd:
      - mkdir -p /usr/local/data
      - mount /dev/disk/by-label/EXTRA_PART /usr/local/data
    elemental:
      install:
        reboot: true
        device: /dev/vda
        debug: true
        config-dir: /etc/elemental
      registration:
        emulate-tpm: true
  machineInventoryLabels:
    cores: "${System Data/CPU/Total Cores}"
    memory: "${System Data/Memory/Total Physical Bytes}"
    registration: fireKK
