apiVersion: elemental.cattle.io/v1beta1
kind: MachineRegistration
metadata:
  name: starter04
  namespace: fleet-local
spec:
  config:
    cloud-config:
      manage_etc_hosts: true
      users:
      - name: root
        passwd: "$6$rounds=4096$cKTGpA.42l0cYct2$jaKlyfu2SDevJ5/HeslSiLPttSTS0C/gku/jZ2Y2AGdsPIxjzmHF5mC5iZexXfHZ3rQC1MQeRNl22JR.fZ/lQ0"
      - name: bms
        passwd: "$6$rounds=4096$cKTGpA.42l0cYct2$jaKlyfu2SDevJ5/HeslSiLPttSTS0C/gku/jZ2Y2AGdsPIxjzmHF5mC5iZexXfHZ3rQC1MQeRNl22JR.fZ/lQ0"
        groups: users, wheel
        sudo: ['ALL=(ALL) NOPASSWD:ALL']
        ssh-authorized-keys:
          - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIEultjv4pCf8QoC7flXkMvEg0uBi0GJxXhWwEB6gyvwk konrad@dell-28
      package_update: true
      package_upgrade: true
      packages:
        - zypper
        - open-vm-tools
      write_files:
      - content: |
          OPTION1="yes"
          OPTION2="false"
        path: "/etc/myservice.conf"
      runcmd:
      - mkdir -p /usr/local/data
      - mount /dev/disk/by-label/EXTRA_PART /usr/local/data
    elemental:
      install:
        reboot: true
        device: /dev/sda
        debug: true
        config-dir: /etc/elemental
      registration:
        emulate-tpm: true
  machineInventoryLabels:
    cores: "${System Data/CPU/Total Cores}"
    memory: "${System Data/Memory/Total Physical Bytes}"
    registration: starter04
