apiVersion: elemental.cattle.io/v1beta1
kind: SeedImage
metadata:
  name: starter01
  namespace: fleet-default
spec:
  baseImage: https://download.opensuse.org/distribution/leap-micro/5.5/appliances/iso/openSUSE-Leap-Micro.x86_64-5.5.0-Default-SelfInstall-Build34.31.install.iso
  cloud-config:
    write_files:
      - content: |
          install:
            extra-partitions:
              - size: 1024
                fs: ext4
                label: EXTRA_PART
        path: /etc/elemental/config.yaml
  registrationRef:
    apiVersion: elemental.cattle.io/v1beta1
    kind: MachineRegistration
    name: starter01
    namespace: fleet-default
