apiVersion: elemental.cattle.io/v1beta1
kind: SeedImage
metadata:
  name: starter01
  namespace: fleet-local
spec:
  baseImage: https://download.opensuse.org/distribution/leap/15.5/iso/openSUSE-Leap-15.5-DVD-x86_64-Build491.1-Media.iso
  cloud-config:
    write_files:
      - content: |
          install:
            extra-partitions:
              - size: 1024
                fs: ext4
                label: EXTRA_PART
        path: /etc/elemental/config.yaml
  registrationRef:
    apiVersion: elemental.cattle.io/v1beta1
    kind: MachineRegistration
    name: starter01
    namespace: fleet-local
