apiVersion: elemental.cattle.io/v1beta1
kind: SeedImage
metadata:
  name: starter01
  namespace: fleet-local
spec:
  baseImage: https://cloud-images.ubuntu.com/jammy/current/jammy-server-cloudimg-amd64.img
  cloud-config:
    write_files:
      - content: |
          install:
            extra-partitions:
              - size: 1024
                fs: ext4
                label: EXTRA_PART
        path: /etc/elemental/config.yaml
  registrationRef:
    apiVersion: elemental.cattle.io/v1beta1
    kind: MachineRegistration
    name: starter01
    namespace: fleet-local
