apiVersion: elemental.cattle.io/v1beta1
kind: SeedImage
metadata:
  name: starter05
  namespace: fleet-local
spec:
  baseImage: http://172.16.1.240/Elemental-0.20240320.iso
  cloud-config:
    write_files:
      - content: |
          install:
            extra-partitions:
              - size: 1024
                fs: ext4
                label: EXTRA_PART
        path: /etc/elemental/config.yaml
  registrationRef:
    apiVersion: elemental.cattle.io/v1beta1
    kind: MachineRegistration
    name: starter05
    namespace: fleet-local
